batch_size: 64
clip_range: 0.2
ent_coef: 0.01
eval_freq: 10000
features_dim: 256
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.0003
log_interval: 1
max_grad_norm: 0.5
n_envs: 4
n_epochs: 10
n_eval_episodes: 20
policy_hidden_sizes: [256, 256]
save_freq: 10000
target_kl: 0.02
total_timesteps: 1000000
value_hidden_sizes: [256, 256]
vf_coef: 0.5
